alias ls='ls --color=auto'
alias paper='cd ~/Dropbox/Papers/'
alias phd='cd ~/Dropbox/Studium/PhD/'
alias code='cd ~/Repositories/Code/'
alias repo=' cd ~/Repositories/'
alias db='cd ~/Dropbox/'
alias mucke='cd ~/Music/'
alias data='cd /media/schlowmo/Data/'
alias ini='sudo openvpn /etc/openvpn/ini_openvpn.conf &'
alias jaer='cd ~/Repositories/DVS/trunk/; sudo ./jAERViewer1.5_linux.sh'
alias franz='cd /home/schlowmo/Dropbox/Privat/franz; ./Franz &'
alias cop='xclip -selection clipboard'
alias mp3id='find . -type f -iname '*.mp3' -exec vbrfix {} {} \;'
alias lsusr='cut -d: -f1 /etc/passwd'
alias ov='tree -I "__pycache__|__init__.py|*.pyc|*.log|*.aux|*.md"'
alias oc='cd ~/ownCloud'

